import type { BomDiffLine, BomLine, Part, Project } from "./types";

export const mockParts: Part[] = [
  {
    id: "part-lm317t-ti",
    mpn: "LM317T",
    manufacturer: "Texas Instruments",
    category: "Regulator",
    description: "Adjustable 1.5 A linear voltage regulator",
    lifecycle_stage: "active",
    score: 92,
    country_of_origin: "US",
    unit_price: 0.42,
    compliance: [
      { standard: "RoHS", status: "pass" },
      { standard: "REACH", status: "pass" },
    ],
    parameters: {
      "Output current": "1.5 A",
      "Input voltage max": "40 V",
      Package: "TO-220",
      "Operating temp": "-40 C to 125 C",
      "Dropout voltage": "2 V",
    },
  },
  {
    id: "part-lm317-onsemi",
    mpn: "LM317ABTG",
    manufacturer: "onsemi",
    category: "Regulator",
    description: "Adjustable positive voltage regulator",
    lifecycle_stage: "nrnd",
    score: 61,
    country_of_origin: "MY",
    unit_price: 0.37,
    compliance: [
      { standard: "RoHS", status: "pass" },
      { standard: "REACH", status: "unknown" },
    ],
    parameters: {
      "Output current": "1.5 A",
      "Input voltage max": "40 V",
      Package: "TO-220",
      "Operating temp": "0 C to 125 C",
      "Dropout voltage": "2.2 V",
    },
  },
  {
    id: "part-lm317-st",
    mpn: "LM317T-DG",
    manufacturer: "STMicroelectronics",
    category: "Regulator",
    description: "Adjustable voltage regulator in TO-220 package",
    lifecycle_stage: "active",
    score: 88,
    country_of_origin: "IT",
    unit_price: 0.39,
    compliance: [
      { standard: "RoHS", status: "pass" },
      { standard: "REACH", status: "pass" },
    ],
    parameters: {
      "Output current": "1.5 A",
      "Input voltage max": "40 V",
      Package: "TO-220",
      "Operating temp": "-40 C to 125 C",
      "Dropout voltage": "2 V",
    },
  },
  {
    id: "part-rc0603-10k-yageo",
    mpn: "RC0603FR-0710KL",
    manufacturer: "Yageo",
    category: "Resistor",
    description: "10 kOhm 1% 0603 thick film resistor",
    lifecycle_stage: "active",
    score: 97,
    country_of_origin: "TW",
    unit_price: 0.01,
    compliance: [
      { standard: "RoHS", status: "pass" },
      { standard: "REACH", status: "pass" },
    ],
    parameters: {
      Resistance: "10 kOhm",
      Tolerance: "1%",
      Package: "0603",
      Power: "0.1 W",
      "Temp coefficient": "100 ppm/C",
    },
  },
  {
    id: "part-rc0603-10k-vishay",
    mpn: "CRCW060310K0FKEA",
    manufacturer: "Vishay",
    category: "Resistor",
    description: "10 kOhm 1% 0603 resistor",
    lifecycle_stage: "active",
    score: 94,
    country_of_origin: "DE",
    unit_price: 0.012,
    compliance: [
      { standard: "RoHS", status: "pass" },
      { standard: "REACH", status: "pass" },
    ],
    parameters: {
      Resistance: "10 kOhm",
      Tolerance: "1%",
      Package: "0603",
      Power: "0.1 W",
      "Temp coefficient": "100 ppm/C",
    },
  },
  {
    id: "part-atmega328p",
    mpn: "ATMEGA328P-AU",
    manufacturer: "Microchip",
    category: "MCU",
    description: "8-bit AVR microcontroller, 32 KB flash",
    lifecycle_stage: "last_time_buy",
    score: 43,
    country_of_origin: "TH",
    unit_price: 2.45,
    compliance: [
      { standard: "RoHS", status: "pass" },
      { standard: "REACH", status: "unknown" },
    ],
    parameters: {
      Core: "AVR",
      Flash: "32 KB",
      SRAM: "2 KB",
      Package: "TQFP-32",
      "Max frequency": "20 MHz",
    },
  },
  {
    id: "part-nrf52840",
    mpn: "nRF52840-QIAA-R",
    manufacturer: "Nordic Semiconductor",
    category: "Wireless MCU",
    description: "Bluetooth 5.4 multiprotocol SoC",
    lifecycle_stage: "active",
    score: 84,
    country_of_origin: "PH",
    unit_price: 4.18,
    compliance: [
      { standard: "RoHS", status: "pass" },
      { standard: "REACH", status: "pass" },
    ],
    parameters: {
      Core: "ARM Cortex-M4F",
      Flash: "1 MB",
      RAM: "256 KB",
      Package: "QFN-73",
      Radio: "Bluetooth LE, Thread, Zigbee",
    },
  },
  {
    id: "part-mcp1700",
    mpn: "MCP1700T-3302E/TT",
    manufacturer: "Microchip",
    category: "Regulator",
    description: "250 mA low quiescent current LDO",
    lifecycle_stage: "active",
    score: 89,
    country_of_origin: "TH",
    unit_price: 0.18,
    compliance: [
      { standard: "RoHS", status: "pass" },
      { standard: "REACH", status: "pass" },
    ],
    parameters: {
      "Output voltage": "3.3 V",
      "Output current": "250 mA",
      Package: "SOT-23-3",
      "Quiescent current": "1.6 uA",
      "Dropout voltage": "178 mV",
    },
  },
  {
    id: "part-opa2134",
    mpn: "OPA2134UA",
    manufacturer: "Texas Instruments",
    category: "Amplifier",
    description: "Audio operational amplifier, dual",
    lifecycle_stage: "obsolete",
    score: 22,
    country_of_origin: "US",
    unit_price: 3.8,
    compliance: [
      { standard: "RoHS", status: "fail" },
      { standard: "REACH", status: "unknown" },
    ],
    parameters: {
      Channels: 2,
      "Supply voltage": "5 V to 36 V",
      "Slew rate": "20 V/us",
      Package: "SOIC-8",
      "Noise density": "8 nV/sqrtHz",
    },
  },
];

function line(partId: string, lineNo: number, qty: number): BomLine {
  const part = mockParts.find((item) => item.id === partId);
  if (!part) throw new Error(`Missing mock part ${partId}`);
  return {
    id: `${partId}-${lineNo}`,
    part_id: part.id,
    line_no: lineNo,
    mpn: part.mpn,
    description: part.description,
    manufacturer: part.manufacturer,
    country_of_origin: part.country_of_origin,
    category: part.category,
    qty,
    unit_price: part.unit_price,
    compliance: part.compliance,
    lifecycle_stage: part.lifecycle_stage,
    score: part.score,
  };
}

export const mockProjects: Project[] = [
  {
    id: "bom-amp-v3",
    name: "Amp-v3 BOM",
    part_count: 5,
    uploaded_at: "2026-06-30",
    owner: "Tirrek",
    lowest_score: 22,
    lines: [
      line("part-rc0603-10k-yageo", 1, 12),
      line("part-lm317t-ti", 2, 4),
      line("part-opa2134", 3, 2),
      line("part-mcp1700", 4, 6),
      line("part-nrf52840", 5, 1),
    ],
  },
  {
    id: "bom-sensor-hub",
    name: "Sensor Hub Rev B",
    part_count: 4,
    uploaded_at: "2026-06-22",
    owner: "Maya",
    lowest_score: 61,
    lines: [
      line("part-rc0603-10k-vishay", 1, 24),
      line("part-lm317-onsemi", 2, 3),
      line("part-atmega328p", 3, 1),
      line("part-mcp1700", 4, 5),
    ],
  },
  {
    id: "bom-controller-dvt",
    name: "Controller DVT",
    part_count: 4,
    uploaded_at: "2026-06-12",
    owner: "Kai",
    lowest_score: 84,
    lines: [
      line("part-rc0603-10k-yageo", 1, 40),
      line("part-lm317-st", 2, 2),
      line("part-nrf52840", 3, 1),
      line("part-mcp1700", 4, 8),
    ],
  },
];

export const mockBomDiff: BomDiffLine[] = [
  {
    ...line("part-rc0603-10k-yageo", 1, 12),
    delta: "changed",
    change_summary: "Qty increased from 10 to 12",
    previous_score: 97,
  },
  {
    ...line("part-lm317t-ti", 2, 4),
    delta: "changed",
    change_summary: "Lifecycle improved from NRND to Active",
    previous_score: 61,
  },
  {
    ...line("part-opa2134", 3, 2),
    delta: "removed",
    change_summary: "Removed obsolete audio amplifier",
    previous_score: 22,
  },
  {
    ...line("part-nrf52840", 4, 1),
    delta: "added",
    change_summary: "Added wireless MCU",
    previous_score: undefined,
  },
];
